package com.cms.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.cms.entity.SQLTest;
import com.cms.repository.SQLTestRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class SQLTestController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private SQLTestRepository sqlTestRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewSQLTest (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		SQLTest n = new SQLTest();
		n.setName(name);
		sqlTestRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<SQLTest> getAllUsers() {
		// This returns a JSON or XML with the users
		return sqlTestRepository.findAll();
	}
}